CREATE DATABASE ELITE_WHEELS_DB;

USE ELITE_WHEELS_DB;

CREATE TABLE CLIENTS_TB(
	ID_CLIENT					INT PRIMARY KEY auto_increment,
    NM_CLIENT					VARCHAR(100) not null,
    DS_EMAIL					VARCHAR(200) not null,
    DS_TELEFONE					VARCHAR(100) not null,
    DS_CPF						VARCHAR(100) not null,
    DS_CNH						VARCHAR(100) not null
);


CREATE TABLE TYPES_CARS_TB(	
	ID_TYPE		INT primary KEY auto_increment,
    NM_TYPE		VARCHAR(100) NOT NULL
);
	
CREATE TABLE CARS_TB(
	ID_CAR				INT primary KEY auto_increment,
    ID_TYPE				INT NOT NULL,
    DS_MODEL			VARCHAR (100) NOT NULL,
    DS_BRAND			VARCHAR (100) NOT NULL,
    NR_YEAR				DATE,
    DS_PLACA			VARCHAR (100),
    FOREIGN KEY (ID_TYPE) REFERENCES TYPES_CARS_TB(ID_TYPE)
);
	

