USE ELITE_WHEELS_DB;

SELECT	*
		FROM CLIENTS_TB;
INSERT INTO CLIENTS_TB(NM_CLIENT, DS_EMAIL, DS_TELEFONE, DS_CPF, DS_CNH )
			VALUES('bruno careca lustrosa', 'brunoCarecaLustrosa@gmail.com', 1154661166, 654631918, 694616641);
            
            
<<<<<<< HEAD
INSERT INTO TB_TYPE_VEHICLE (DS_TYPE)
							VALUES('BATMAN');

INSERT INTO TB_VEHICLE (ID_TYPE, DS_MODEL, DS_BRAND, NR_YEAR, DS_PLATE)
						VALUES(1, 'BATMOVEL', 'BAT', 1980, 'ASDA-4963');

	SELECT 	DS_TYPE					AS Tipo,
			DS_MODEL				AS Modelo,
			DS_BRAND				AS Marca,
			NR_YEAR					AS Ano,
			DS_PLATE				AS Placa
	FROM	TB_VEHICLE				AS V
	INNER JOIN TB_TYPE_VEHICLE 		AS _TYPES ON _TYPES.ID_TYPE = V.ID_TYPE;

=======
            

UPDATE CLIENTS_TB 
SET 
    NM_CLIENT = 'jajajja',
    DS_EMAIL = 'aaaaaaa',
    DS_TELEFONE = '1111111111',
    DS_CPF = '1111111111111',
    DS_CNH = '111111111111111'
WHERE
    ID_CLIENT = 2;
    
    
    INSERT INTO	TYPES_CARS_TB (NM_TYPE)
							VALUES('AUTOBOTS');
                            
	INSERT INTO CARS_TB (ID_TYPE, DS_MODEL, DS_BRAND, NR_YEAR, DS_PLACA)
				VALUES(2, 'OPTIMUS PRIME', 'AUTOBOTS', '2010/05/01','ABC-113');
	
		SELECT 	NM_TYPE 			AS tipo,
				DS_MODEL			AS Modelo,
				DS_PLACA			AS Ano
		FROM 	CARS_TB				AS C
  INNER JOIN 	TYPES_CARS_TB  		AS TC ON TC.ID_TYPE = C.ID_TYPE;
			
>>>>>>> 5afcf58fad13540a412c06bfba8675ff9e69516d
