USE ELITE_WHEELS_DB;

SELECT	*
		FROM CLIENTS_TB;
INSERT INTO CLIENTS_TB(NM_CLIENT, DS_EMAIL, DS_TELEFONE, DS_CPF, DS_CNH )
			VALUES('bruno careca lustrosa', 'brunoCarecaLustrosa@gmail.com', 1154661166, 654631918, 694616641);
            
            
INSERT INTO TB_TYPE_VEHICLE (DS_TYPE)
							VALUES('BATMAN');

INSERT INTO TB_VEHICLE (ID_TYPE, DS_MODEL, DS_BRAND, NR_YEAR, DS_PLATE)
						VALUES(1, 'BATMOVEL', 'BAT', 1980, 'ASDA-4963');

	SELECT 	DS_TYPE					AS Tipo,
			DS_MODEL				AS Modelo,
			DS_BRAND				AS Marca,
			NR_YEAR					AS Ano,
			DS_PLATE				AS Placa
	FROM	TB_VEHICLE				AS V
	INNER JOIN TB_TYPE_VEHICLE 		AS _TYPES ON _TYPES.ID_TYPE = V.ID_TYPE;

